# Generated by Django 4.2.1 on 2023-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailPhish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='status',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='counter_is',
            field=models.CharField(blank=True, max_length=242, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='unique_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
