# Generated by Django 4.2.1 on 2023-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailPhish', '0003_alter_usermodel_counter_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='counter_is',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
